### ISSUE TITLE
Can't Test in Office Online

### ISSUE THREAD

**Issue by sambraley** [OfficeDev/Word-Add-in-AngularJS-Client-OAuth#2]
Tried testing this sample using Word Online by uploading the manifest, but in the task pane it just says "**Add-in Error:** This add-in is not supported in this version of Office." It doesn't seem to have any details about why it's not supported, but I figured I would let y'all know in case it should be working in Word Online.

**Comment by dougperkes** [comment]
Thanks for the feedback @samuelbraley. At this point Office Online does not yet support the dialog API which is demonstrated in this sample. The reason you see that error is because the following is included in the manifest file, which prevents the add-in from running if the DialogAPI is missing:

``` xml
  <Requirements> 
   <Sets DefaultMinVersion="1.1"> 
     <Set Name="DialogAPI"/> 
   </Sets> 
 </Requirements> 
```

More details on the dialog API and supported platforms can be found [here](https://github.com/OfficeDev/office-js-docs/blob/3fffaa1ce910d9c85026dbd93c6299d36eefcf09/reference/shared/officeui.md).
