### ISSUE TITLE
Unable to see Sideloaded manifest in Office 2016

### ISSUE THREAD

**Issue by SoftEngrLACA** [OfficeDev/Word-Add-in-AngularJS-Client-OAuth#3]
Followed the instructions "Have a location to publish you add-in manifest. See Publish your Office Add-in" and used the manifest manifest-client-side-auth-sample.xml. SourceLocation was changed to point to source on a Web server. Followed the instructions for Sideload Office Add-ins for testing at 
http://dev.office.com/docs/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins
The add-in does not show up in Office 2016.

**Comment by Rick-Kirkham** [comment]
When you say it does not show up, do you mean it does not appear in the list of add-ins when you click **Shared Folder** in the Office Add-ins dialog?

**Comment by SoftEngrLACA** [comment]
Yes, exactly. 

And thanks for responding.Regards,Wick

```
  From: Rick-Kirkham <notifications@github.com>
```

 To: OfficeDev/Word-Add-in-AngularJS-Client-OAuth Word-Add-in-AngularJS-Client-OAuth@noreply.github.com 
Cc: SoftEngrLACA wick_sw_engineer@yahoo.com; Author author@noreply.github.com
 Sent: Friday, August 12, 2016 1:54 PM
 Subject: Re: [OfficeDev/Word-Add-in-AngularJS-Client-OAuth] Unable to see Sideloaded manifest in Office 2016 (#3)

When you say it does not show up, do you mean it does not appear in the list of add-ins when you click Shared Folder in the Office Add-ins dialog?—

**Comment by Rick-Kirkham** [comment]
I'm not able to reproduce the issue. If I put the manifest, unchanged, into my share, close all Office applications and reopen [BE SURE YOU DO THAT!], then it shows up. Off the top of my head, I would guess that your manifest file is invalid for some reason. You may have inadvertently corrupted it when you changed the SourceLocation. See if the original manifest will show up. Another possibility is that the folder you put the manifest in is not the one that you setup in the Trust Center. Maybe you misspelled it. If you put other manifest files from other samples, unchanged, into that shared folder, do they show up in the Office Add-ins dialog?

**Comment by Rick-Kirkham** [comment]
It occurs to me now that we don't ever explain how to share a folder. 
1. Right click the folder, and select **Properties**.
2. Open the **Sharing** tab.
3. On the **Choose people ...** page, add anyone who will be using the add-in. Since you are developing, that is probably just you. You will need Read/Write permission to the folder. 
4. Click **Share**.
5. Click **Done**.
6. Click **Close**.

Now you carry out the instructions at:  at 
http://dev.office.com/docs/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

UPDATE: I have added these instructions to that topic and the new version should be published soon.
